# This is a basic workflow to help you get started with Actions

name: Reject Unauthorized PRs

# Controls when the workflow will run
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_access:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Reject Unauthorized PRs

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout repository

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Get collaborators
        shell: bash
        env:
          SECRET: ${{ secrets.mySecret }}
        run: |
         curl -X GET https://api.github.com/repos/stuartko/template-spec-samples/collaborators/${{ github.actor }} -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
         echo  https://api.github.com/repos/stuartko/template-spec-samples/collaborators/${{ github.actor }}
         $result = curl -X GET https://api.github.com/repos/stuartko/template-spec-samples/collaborators/${{ github.actor }} -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
         echo "::set-output name=collaboratorResult::$result"
         echo "Result is $result"

      - name: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
